### ISSUE TITLE
cf-mta-deploy-service: is it deployed by SAP or customer?

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP/cf-mta-deploy-service#128]
Hi

As CF provider, SAP deploys the **cf-mta-deploy-service** service by default or customer has to install cf-mta-deploy-service manually.

Is there any command to know what services are deployed by-default in CF by SAP. is it `cf plugins` command helps us?

Thanks, Manju

**Comment by mptsonev** [comment]
Hi Manju,

You can check the deployed services, available in your space, by running the "cf marketplace" command. The Deploy Service application is deployed to the CF installation by SAP and the customer consumes that installation using the MtaPlugin.

Best,
Mihail

**Comment by manjunathgudisi** [comment]
Thanks buddy.

I ran `cf marketplace` command and I don’t see the `deploy-service` in the list.

According to you, SAP had installed it already. However, I don’t see it in the list. Why is that so?

Can you share your screenshot by running the `cf marketplace` command if possible?

Thanks, Manju

**Comment by mptsonev** [comment]
The Deploy Service is not an actual service, available in the martketplace. You don't need to bind your applications to it or whatsoever. It is an application, which is deployed in the SAP_xsa/deploy-service org/space and you can reach it with the MtaPlugin.
